const express = require("express");
const { isVerifiedUser, restrictTo } = require("../middlewares/tokenVerification");
const { getFinanceReport } = require("../controllers/reportController");
const { getProfitReport } = require("../controllers/profitController");
const { getPricingRecommendations } = require("../controllers/pricingController");
const { getOwnerBriefing } = require("../controllers/copilotController");
const { getPaymentReconciliation } = require("../controllers/paymentReconciliationController");
const { getFraudSignals } = require("../controllers/fraudController");
const { exportOrdersCsv } = require("../controllers/reportExportController");
const { getAuditEvents } = require("../controllers/auditEventController");
const router = express.Router();
router.get("/finance", isVerifiedUser, restrictTo("Admin"), getFinanceReport);
router.get("/profit", isVerifiedUser, restrictTo("Admin"), getProfitReport);
router.get("/pricing-recommendations", isVerifiedUser, restrictTo("Admin"), getPricingRecommendations);
router.get("/owner-briefing", isVerifiedUser, restrictTo("Admin"), getOwnerBriefing);
router.get("/payment-reconciliation", isVerifiedUser, restrictTo("Admin"), getPaymentReconciliation);
router.get("/fraud-signals", isVerifiedUser, restrictTo("Admin"), getFraudSignals);
router.get("/export/orders.csv", isVerifiedUser, restrictTo("Admin"), exportOrdersCsv);
router.get("/audit-events", isVerifiedUser, restrictTo("Admin"), getAuditEvents);
module.exports = router;
