const express = require("express");
const { isVerifiedUser, restrictTo } = require("../middlewares/tokenVerification");
const { getFinanceReport } = require("../controllers/reportController");
const { getProfitReport } = require("../controllers/profitController");
const { getPricingRecommendations } = require("../controllers/pricingController");
const { getOwnerBriefing } = require("../controllers/copilotController");
const { getPaymentReconciliation } = require("../controllers/paymentReconciliationController");
const { getFraudSignals } = require("../controllers/fraudController");
const { exportOrdersCsv } = require("../controllers/reportExportController");
const { getAuditEvents, getAuditRetention } = require("../controllers/auditEventController");
const { getAcknowledgements, acknowledgeBriefing } = require("../controllers/briefingAcknowledgementController");
const rateLimit = require("../middlewares/rateLimit");
const { getAdminActivitySummary } = require("../controllers/adminActivityController");
const router = express.Router();
router.get("/finance", isVerifiedUser, restrictTo("Admin"), getFinanceReport);
router.get("/profit", isVerifiedUser, restrictTo("Admin"), getProfitReport);
router.get("/pricing-recommendations", isVerifiedUser, restrictTo("Admin"), getPricingRecommendations);
router.get("/owner-briefing", isVerifiedUser, restrictTo("Admin"), getOwnerBriefing);
router.get("/payment-reconciliation", isVerifiedUser, restrictTo("Admin"), getPaymentReconciliation);
router.get("/fraud-signals", isVerifiedUser, restrictTo("Admin"), getFraudSignals);
router.get("/export/orders.csv", rateLimit({ windowMs: 60_000, max: 30 }), isVerifiedUser, restrictTo("Admin"), exportOrdersCsv);
router.get("/audit-events", isVerifiedUser, restrictTo("Admin"), getAuditEvents);
router.get("/audit-events/retention", isVerifiedUser, restrictTo("Admin"), getAuditRetention);
router.get("/admin-activity", isVerifiedUser, restrictTo("Admin"), getAdminActivitySummary);
router.get("/owner-briefing/acknowledgements", isVerifiedUser, restrictTo("Admin"), getAcknowledgements);
router.post("/owner-briefing/acknowledgements", isVerifiedUser, restrictTo("Admin"), acknowledgeBriefing);
module.exports = router;
